Minimum Viable Product:

1. Predict the game outcome in the testing dataset based on match history (Potentially included player's information)
2. Recommend the hero for player based on player's playing history and line up in both teams

In [1]:
import dota2api as d2
import os
import pandas as pd
import numpy as np
import ipdb

In [2]:
d2_key = os.environ['D2_API_KEY']

In [2]:
api = d2.Initialise()

### 2015-11-16 Familiar with API

* Get to know what each function do and the structure of data returned

### (1) Match Detail

* The players column contain a lot of information: the hero's name and id. They are needed for game prediction
* It needs further check

In [12]:
match_id_example = 1980394727

In [14]:
match = api.get_match_details(match_id_example)

In [7]:
type(match)

dota2api.src.response.Dota2Dict

In [8]:
match.keys()

[u'engine',
 u'barracks_status_dire',
 u'match_id',
 u'lobby_name',
 u'start_time',
 u'match_seq_num',
 u'radiant_win',
 u'barracks_status_radiant',
 u'cluster',
 u'lobby_type',
 u'first_blood_time',
 u'negative_votes',
 u'tower_status_radiant',
 u'game_mode',
 u'duration',
 u'human_players',
 u'tower_status_dire',
 u'positive_votes',
 u'cluster_name',
 u'players',
 u'game_mode_name',
 u'leagueid']

In [9]:
match['radiant_win']

True

In [6]:
match_df = pd.DataFrame.from_dict(match)

In [7]:
match_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10 entries, 0 to 9
Data columns (total 22 columns):
barracks_status_dire       10 non-null int64
barracks_status_radiant    10 non-null int64
cluster                    10 non-null int64
cluster_name               10 non-null object
duration                   10 non-null int64
engine                     10 non-null int64
first_blood_time           10 non-null int64
game_mode                  10 non-null int64
game_mode_name             10 non-null object
human_players              10 non-null int64
leagueid                   10 non-null int64
lobby_name                 10 non-null object
lobby_type                 10 non-null int64
match_id                   10 non-null int64
match_seq_num              10 non-null int64
negative_votes             10 non-null int64
players                    10 non-null object
positive_votes             10 non-null int64
radiant_win                10 non-null bool
start_time                 10 non-null i

### (2) Match History

* Get_match_history will return 100 most matches for player
* Totally 500 matches for player are stored
* only line-up information included

In [50]:
hao = 110435207

In [23]:
hist = api.get_match_history(account_id=hao)

In [25]:
hist_df=pd.DataFrame.from_dict(hist)

In [27]:
hist_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100 entries, 0 to 99
Data columns (total 5 columns):
matches              100 non-null object
num_results          100 non-null int64
results_remaining    100 non-null int64
status               100 non-null int64
total_results        100 non-null int64
dtypes: int64(4), object(1)
memory usage: 4.7+ KB


In [28]:
hist_df.head(1)

matches  num_results  \
0  {u'dire_team_id': 0, u'match_id': 1980394727, ...          100   

   results_remaining  status  total_results  
0                172       1            272

In [30]:
hist_df.matches[0]

{u'dire_team_id': 0,
 u'lobby_type': 0,
 u'match_id': 1980394727,
 u'match_seq_num': 1747751775,
 u'players': [{u'account_id': 301152448, u'hero_id': 101, u'player_slot': 0},
  {u'account_id': 110435207, u'hero_id': 30, u'player_slot': 1},
  {u'account_id': 45431908, u'hero_id': 72, u'player_slot': 2},
  {u'account_id': 4294967295, u'hero_id': 18, u'player_slot': 3},
  {u'account_id': 4294967295, u'hero_id': 81, u'player_slot': 4},
  {u'account_id': 283908220, u'hero_id': 77, u'player_slot': 128},
  {u'account_id': 4294967295, u'hero_id': 104, u'player_slot': 129},
  {u'account_id': 4294967295, u'hero_id': 60, u'player_slot': 130},
  {u'account_id': 4294967295, u'hero_id': 8, u'player_slot': 131},
  {u'account_id': 193629672, u'hero_id': 73, u'player_slot': 132}],
 u'radiant_team_id': 0,
 u'start_time': 1449297417}

In [31]:
hist_2 = api.get_match_history(193629672)

In [33]:
hist_2_df = pd.DataFrame.from_dict(hist_2)

In [34]:
hist_2_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100 entries, 0 to 99
Data columns (total 5 columns):
matches              100 non-null object
num_results          100 non-null int64
results_remaining    100 non-null int64
status               100 non-null int64
total_results        100 non-null int64
dtypes: int64(4), object(1)
memory usage: 4.7+ KB


In [35]:
hist_2_df.head(2)

matches  num_results  \
0  {u'dire_team_id': 0, u'match_id': 2003891041, ...          100   
1  {u'dire_team_id': 0, u'match_id': 2003822317, ...          100   

   results_remaining  status  total_results  
0                400       1            500  
1                400       1            500

In [36]:
match_burning = api.get_match_details(2006107189)

In [37]:
match_burning.keys()

[u'engine',
 u'barracks_status_dire',
 u'tower_status_radiant',
 u'match_id',
 u'lobby_name',
 u'start_time',
 u'match_seq_num',
 u'barracks_status_radiant',
 u'cluster',
 u'first_blood_time',
 u'negative_votes',
 u'game_mode',
 u'duration',
 u'radiant_win',
 u'lobby_type',
 u'tower_status_dire',
 u'picks_bans',
 u'positive_votes',
 u'human_players',
 u'radiant_captain',
 u'cluster_name',
 u'players',
 u'game_mode_name',
 u'leagueid',
 u'dire_captain']

In [39]:
match_burning['players'][9]

{u'ability_upgrades': [{u'ability': 5173, u'level': 1, u'time': 646},
  {u'ability': 5174, u'level': 2, u'time': 693},
  {u'ability': 5175, u'level': 3, u'time': 758},
  {u'ability': 5175, u'level': 4, u'time': 804},
  {u'ability': 5175, u'level': 5, u'time': 878},
  {u'ability': 5176, u'level': 6, u'time': 956},
  {u'ability': 5175, u'level': 7, u'time': 1026},
  {u'ability': 5174, u'level': 8, u'time': 1100},
  {u'ability': 5174, u'level': 9, u'time': 1257},
  {u'ability': 5174, u'level': 10, u'time': 1373},
  {u'ability': 5176, u'level': 11, u'time': 1429},
  {u'ability': 5002, u'level': 12, u'time': 1656},
  {u'ability': 5002, u'level': 13, u'time': 1920}],
 u'account_id': 90892734,
 u'assists': 2,
 u'deaths': 4,
 u'denies': 16,
 u'gold': 1321,
 u'gold_per_min': 435,
 u'gold_spent': 9170,
 u'hero_damage': 9475,
 u'hero_healing': 0,
 u'hero_id': 39,
 u'hero_name': u'Queen of Pain',
 u'item_0': 21,
 u'item_0_name': u'Ogre Club',
 u'item_1': 63,
 u'item_1_name': u'Power Treads',
 u'it

In [45]:
burning = 90892734

In [40]:
hist_burning = api.get_match_history(burning)

In [42]:
hist_burning_df = pd.DataFrame.from_dict(hist_burning)

In [43]:
hist_burning_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100 entries, 0 to 99
Data columns (total 5 columns):
matches              100 non-null object
num_results          100 non-null int64
results_remaining    100 non-null int64
status               100 non-null int64
total_results        100 non-null int64
dtypes: int64(4), object(1)
memory usage: 4.7+ KB


In [44]:
hist_burning_df.head(1)

matches  num_results  \
0  {u'dire_team_id': 0, u'match_id': 1993675690, ...          100   

   results_remaining  status  total_results  
0                400       1            500

### (3) Get player summary

- Included some basic person information

In [63]:
hao_steamid = '76561198070700935'

In [64]:
plyer_summary = api.get_player_summaries(steamids=hao_steamid)

In [65]:
plyer_summary

{u'players': [{u'avatar': u'https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/fe/fef49e7fa7e1997310d705b2a6158ff8dc1cdfeb.jpg',
   u'avatarfull': u'https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/fe/fef49e7fa7e1997310d705b2a6158ff8dc1cdfeb_full.jpg',
   u'avatarmedium': u'https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/fe/fef49e7fa7e1997310d705b2a6158ff8dc1cdfeb_medium.jpg',
   u'communityvisibilitystate': 1,
   u'lastlogoff': 1449387775,
   u'personaname': u'edwarddh101',
   u'personastate': 0,
   u'profilestate': 1,
   u'profileurl': u'http://steamcommunity.com/id/edwarddh101/',
   u'steamid': u'76561198070700935'}]}

### (4) get_match_history_by_seq_num

* The main method we will use to get match detail
* The value in the key=matches is equal to the match detail
* The method will ignore the invalid key and start from next valid key
* The seq_num is in time order.

In [84]:
# try the invalid seq_num
match_seq_invalid = api.get_match_history_by_seq_num(1747751776)

In [68]:
matches_df = pd.DataFrame.from_dict(matches)

In [70]:
matches_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100 entries, 0 to 99
Data columns (total 2 columns):
matches    100 non-null object
status     100 non-null int64
dtypes: int64(1), object(1)
memory usage: 2.3+ KB


In [71]:
matches_df.head(1)

matches  status
0  {u'tower_status_dire': 4, u'engine': 1, u'barr...       1

In [81]:
df_match_detail_by_seq = pd.DataFrame.from_dict(matches_df.matches[0])

In [82]:
df_match_detail_by_seq.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10 entries, 0 to 9
Data columns (total 19 columns):
barracks_status_dire       10 non-null int64
barracks_status_radiant    10 non-null int64
cluster                    10 non-null int64
duration                   10 non-null int64
engine                     10 non-null int64
first_blood_time           10 non-null int64
game_mode                  10 non-null int64
human_players              10 non-null int64
leagueid                   10 non-null int64
lobby_type                 10 non-null int64
match_id                   10 non-null int64
match_seq_num              10 non-null int64
negative_votes             10 non-null int64
players                    10 non-null object
positive_votes             10 non-null int64
radiant_win                10 non-null bool
start_time                 10 non-null int64
tower_status_dire          10 non-null int64
tower_status_radiant       10 non-null int64
dtypes: bool(1), int64(17), object(1)
memor

### Build a dota2 api bot to get match detail by get_match_history_by_seq_num

* Try to get one month data.
* The start point match_seq_num = 1704401237, time = 2015-11-11

In [3]:
match_temp = api.get_match_details(1928833457)

In [6]:
match_temp['start_time']

1447241966

In [10]:
import datetime
print(
    datetime.datetime.fromtimestamp(
        int(match_temp['start_time'])
    ).strftime('%Y-%m-%d %H:%M:%S')
)

2015-11-11 03:39:26


In [11]:
match_temp['match_seq_num']

1704401237

In [13]:
match_id_example-match_temp['match_seq_num']

275993490

## 2015-11-17, build API on EC2 and store the data on S3

* Optimize API bot 

-- Separate process of get the data and store in the database
-- vectorize some of function in apibot and add function to check current match in file

## 2015-11-18 EDA on sample data

Findings:
1) Some exception: Different game mode may make the data frame looks different - less player in solo mode, mode information in captain mode

In [2]:
with open('Data_collection/match_history_sample.json') as f:
    match_json_array = []
    for line in f:
        match_json_array.append(line)

In [5]:
len(match_json_array)

300

In [3]:
data=pd.DataFrame(match_json_array)


In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 300 entries, 0 to 299
Data columns (total 1 columns):
0    300 non-null object
dtypes: object(1)
memory usage: 4.7+ KB


In [6]:
data.head(1)

0
0  {"status": 1, "matches": [{"tower_status_dire"...

In [4]:
t = map(lambda x: pd.read_json(x), match_json_array)

In [10]:
type(t)

list

In [11]:
type(t[0])

pandas.core.frame.DataFrame

In [5]:
df = pd.concat(t,ignore_index=True)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30000 entries, 0 to 29999
Data columns (total 2 columns):
matches    30000 non-null object
status     30000 non-null int64
dtypes: int64(1), object(1)
memory usage: 703.1+ KB


In [10]:
df.head(1)

matches  status
0  {u'tower_status_dire': 6, u'engine': 1, u'barr...       1

In [17]:
def list_df(lst, axis):
    return pd.concat(map(lambda x:pd.DataFrame.from_dict(x), lst), axis=axis)

In [21]:
heroes = api.get_heroes()

* Totally 112 heroes(id: 1-113) and 1 (id: 108) is not in current dota2 and 1(id: 113) is not in patch(6.85b) I studied 
* Some data cleaning is needed:
    - Only 'player' and 'radiant_win' is needed for first model
    - Set the human_player equal to 10
    - Set the duration larger than 10 min
    - might be need check player leave time
    - might be need to check the game mode

In [6]:
df = pd.DataFrame(df.matches.tolist())

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30000 entries, 0 to 29999
Data columns (total 36 columns):
barracks_status_dire       30000 non-null int64
barracks_status_radiant    30000 non-null int64
cluster                    30000 non-null int64
dire_captain               263 non-null float64
dire_guild_id              2 non-null float64
dire_guild_logo            2 non-null float64
dire_guild_name            2 non-null object
dire_logo                  23 non-null float64
dire_name                  23 non-null object
dire_team_complete         23 non-null float64
dire_team_id               23 non-null float64
duration                   30000 non-null int64
engine                     30000 non-null int64
first_blood_time           30000 non-null int64
game_mode                  30000 non-null int64
human_players              30000 non-null int64
leagueid                   30000 non-null int64
lobby_type                 30000 non-null int64
match_id                   30000 non-nu

In [7]:
df_log = df[df['human_players']==10]

In [46]:
feature = ['players', 'radiant_win']
df_log = df_log[feature]

In [47]:
df_log.head(2)

players radiant_win
0  [{u'gold_spent': 8950, u'gold': 2609, u'deaths...        True
1  [{u'gold_spent': 17970, u'gold': 3056, u'death...        True

In [48]:
df_log.columns

Index([u'players', u'radiant_win'], dtype='object')

In [8]:
def match_features(players):
    vec = np.zeros(224, dtype=np.int)
    loc = np.append(np.zeros(5, dtype=np.int), np.ones(5, dtype=np.int)*112)
    loc+=map(lambda x: x['hero_id']-1, players)
    vec[loc]=1
    return vec
#     ipdb.set_trace()
#     return pd.DataFrame(vec,index=np.arange(1,226),columns=[0]).T

In [50]:
match_features(df_log['players'][0]).sum()

10

In [32]:
def matches_features(df):
    df_feature = df['players'].apply(lambda x: match_features(x))
    X = pd.DataFrame(df_feature.tolist())
    y = df['radiant_win']
    return X, y

In [33]:
X, y = matches_features(df_log)

In [34]:
# Sanity Check
X.shape, y.shape

((29044, 224), (29044,))

In [17]:
df_log['radiant_win'].count()

29044

In [18]:
df_log['radiant_win'].sum()

15274

In [13]:
# Run a base Logistic Model on the data
# 10% data will used as testing data, and CV will be used for training data

from sklearn import cross_validation, linear_model
from sklearn.ensemble import RandomForestClassifier

In [57]:
X_train, X_test, y_train, y_test = cross_validation.train_test_split(X, y, test_size=0.1)

In [119]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((26139, 224), (2905, 224), (26139,), (2905,))

In [120]:
clf_log= linear_model.LogisticRegressionCV()

In [121]:
clf_log.fit(X_train, y_train)

LogisticRegressionCV(Cs=10, class_weight=None, cv=None, dual=False,
           fit_intercept=True, intercept_scaling=1.0, max_iter=100,
           multi_class='ovr', n_jobs=1, penalty='l2', refit=True,
           scoring=None, solver='lbfgs', tol=0.0001, verbose=0)

In [124]:
clf_log.score(X_test, y_test)

0.53390705679862305

In [56]:
clf_log_r = linear_model.LogisticRegression()
cross_validation.cross_val_score(clf_log_r, X, y, cv=5)

array([ 0.60027543,  0.59149595,  0.59803753,  0.58977449,  0.5922865 ])

In [23]:
clf_log_r = linear_model.LogisticRegression(penalty='l1')
cross_validation.cross_val_score(clf_log_r, X, y, cv=5)

array([ 0.59924255,  0.59080737,  0.59975899,  0.58960234,  0.59383609])

In [14]:
clf_rf = RandomForestClassifier(n_estimators=100, n_jobs=-1)
cross_validation.cross_val_score(clf_rf, X, y, cv=5)

array([ 0.57014977,  0.57496987,  0.55982097,  0.56636254,  0.57610193])

In [22]:
clf_rf = RandomForestClassifier(n_estimators=100, n_jobs=-1, max_depth=30)
cross_validation.cross_val_score(clf_rf, X, y, cv=5)

array([ 0.58564297,  0.57496987,  0.57996213,  0.56705113,  0.58367769])

In [15]:
clf_rf = RandomForestClassifier(n_estimators=1000, n_jobs=-1)
cross_validation.cross_val_score(clf_rf, X, y, cv=5)

array([ 0.58306077,  0.57892925,  0.57634705,  0.5735927 ,  0.58264463])

In [ ]:
# Use GridSearch for clf_rf



In [28]:
df_log.lobby_type.value_counts()

0    17576
7    11425
1       43
dtype: int64

In [29]:
df_log_CM = df_log[df_log.lobby_type==0]

In [30]:
df_log_CM.game_mode.value_counts()

1     13818
4      2584
18      455
5       372
3       184
13       71
2        62
12       27
16        3
dtype: int64

In [31]:
df_log_CM_AP = df_log_CM[df_log_CM.game_mode==1]

In [35]:
X, y = matches_features(df_log_CM_AP)
# clf_log_r = linear_model.LogisticRegression()
cross_validation.cross_val_score(clf_log_r, X, y, cv=5)

array([ 0.59442836,  0.58321274,  0.59732272,  0.59153401,  0.58979001])

### Re-Check the detail of data, EDA

* The first model findings:
    - The logistic model has better result than Random Forest
    - The model didn't involve heroes interaction
    - The model didn't account for player's information. This might be a big factor to influence win/lose, try to limited the matches between same level of players.
    
* Some basic stats:
    ```
    INVALID = -1;
	CASUAL_MATCH = 0;
	PRACTICE = 1;
	TOURNAMENT = 2;
	COOP_BOT_MATCH = 4;
	LEGACY_TEAM_MATCH = 5;
	LEGACY_SOLO_QUEUE_MATCH = 6;
	COMPETITIVE_MATCH = 7;
	CASUAL_1V1_MATCH = 8;
    ```
        - The CASUAL_MATCH and cmpetitive_match(MMR) are most used, this might lead to two different models. 

In [37]:
df.head(1).T

0
matches  {u'tower_status_dire': 6, u'engine': 1, u'barr...
status                                                   1

In [17]:
df_players = df.pop('players')

In [20]:
df_players_10=pd.DataFrame(df_players.tolist())

In [24]:
pd.DataFrame(df_players_10.iloc[:,0].tolist()).head(1).T

0
ability_upgrades  [{u'time': 475, u'ability': 5163, u'level': 1}...
account_id                                                117421467
additional_units                                                NaN
assists                                                          11
deaths                                                            4
denies                                                            2
gold                                                           2609
gold_per_min                                                    408
gold_spent                                                     8950
hero_damage                                                    5133
hero_healing                                                    551
hero_id                                                          37
item_0                                                           65
item_1                                                          100
item_2                                                            0
item_3                                                           30
item_4                                                          188
item_5                                                           29
kills                                                             2
last_hits                                                        91
leaver_status                                                     0
level                                                            14
player_slot                                                       0
tower_damage                                                    148
xp_per_min                                                      400

In [31]:
df['lobby_type'].value_counts()

0    17625
7    11425
4      678
8      229
1       43
dtype: int64

* Check only MMR matches

In [24]:
df_mmr = df[df['lobby_type']==7]

In [44]:
# df_mmr.info()
# less than 1% matches are in Captain Mode

In [62]:
cd model/

/home/hao/Repos/DSI/DOTA2_Recommendation-System/model


In [67]:
import log_model_heroes 

In [69]:
log_model_heroes.model_lg(df_mmr)

model_lg CV: [ 0.59623797  0.59824945  0.59912473  0.58249453  0.60070053]


In [70]:
log_model_heroes.model_rf(df_mmr)

model_rf CV score: [ 0.5279965   0.51422319  0.54004376  0.53698031  0.5293345 ]


In [71]:
log_model_heroes.model_lg(df_log)

model_lg CV: [ 0.60027543  0.59149595  0.59803753  0.58977449  0.5922865 ]


In [72]:
log_model_heroes.model_rf(df_log)

model_rf CV score: [ 0.53572043  0.55052505  0.54054054  0.53761405  0.5297865 ]


In [26]:
# Chceck the game mode in df_mmr
df_mmr['game_mode'].value_counts()

22    11270
2       155
dtype: int64

In [27]:
df_log['game_mode'].value_counts()

1     13818
22    11270
4      2584
18      455
5       372
2       260
3       184
13       71
12       27
16        3
dtype: int64

*  Mode 1 is All-pick
*  Mode 2 is Captain Mode
*  Mode 22 is Ranked All-pick

### Improvment needed for outcome predicted model
 - Tune the parameters in Logistic and Random Forester model
 - Adding Two heroes interaction in the model, 24,976-112 features were added to model. A pair of heroes on the same side or on the each side 